### ISSUE TITLE
Doesn’t work programmatically

### ISSUE THREAD

**Issue by tomek-he-him** [shamasis/sleep-ms#1]
Hi, the JS usage doesn’t work. Try running this script in node:

``` js
const sleep = require('sleep-ms');
setTimeout(() => console.log('500 ms passed!'), 500);
sleep(1000);
console.log('1000 ms passed!');
```

Here’s the output:

```
1000 ms passed!
500 ms passed!
```

BTW, the only way to implement `sleep` in native JS is to block execution:

``` js
const begin = Date.now();
while (true) if (Date.now() - begin >= ms) break;
```

– but that freezes a thread completely and is usually a very bad idea. On a single-thread processor this would freeze the whole system!

**Comment by tomek-he-him** [comment]
…but the CLI works like a charm and is pretty useful :) I’ll happily star this module if you take the JS thing out of the docs :)

**Comment by shamasis** [comment]
Actually CLI was the main thing I created this for.

The JS API does not block the code running scope. It simply acts as setTimeout. It's stupid - I know! But, there's no use case for it. Blocking execution is not really a good thing.

I think I will remove the JS related doc like you've suggested.

**Comment by shamasis** [comment]
Also, version 1 of this module used the blocking method, which I replaced with timeout in v2.

**Comment by tomek-he-him** [comment]
> I think I will remove the JS related doc like you've suggested.

Good thing! :+1: 

> Actually CLI was the main thing I created this for.

It’s the only thing I need it for :)
